version: "3"

services:
  frontend:
    build:
      context: ./plant_moi_client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - backend
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    restart: always